[[rulesets]]
group = "🎯 全球直连"
ruleset = "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/UnBan.list"

[[rulesets]]
group = "🛑 全球拦截"
ruleset = "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanAD.list"

[[rulesets]]
group = "🛑 全球拦截"
ruleset = "https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/BanProgramAD.list"
