#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
WORK_DIR="${WORK_DIR:-$SCRIPT_DIR/tmp/e2e}"
CONFIG_DEPOT_SOURCE_DIR="${CONFIG_DEPOT_SOURCE_DIR:-$ROOT_DIR/config-depot}"
CONFIG_DEPOT_BINARY="${CONFIG_DEPOT_BINARY:-$CONFIG_DEPOT_SOURCE_DIR/config-depot}"
CONFIG_DEPOT_DATA_DIR="${CONFIG_DEPOT_DATA_DIR:-$ROOT_DIR/config-depot/data}"
CONFIG_DEPOT_ADDR="${CONFIG_DEPOT_ADDR:-127.0.0.1:18080}"
GITHUB_TOKEN_FILE="${GITHUB_TOKEN_FILE:-$CONFIG_DEPOT_DATA_DIR/github_token}"

SUBCONVERTER_DIR="${SUBCONVERTER_DIR:-$WORK_DIR/subconverter}"
SUBCONVERTER_BASE_PATH="${SUBCONVERTER_BASE_PATH:-_SubConfig}"
ACL4SSR_BASE_PATH="${ACL4SSR_BASE_PATH:-_ACL4SSR}"
SUBCONFIG_DIR="${SUBCONFIG_DIR:-$SUBCONVERTER_DIR/$SUBCONVERTER_BASE_PATH}"

UPLOAD_SECRET_FILE="${UPLOAD_SECRET_FILE:-$CONFIG_DEPOT_DATA_DIR/upload_secret}"
UPLOAD_TOKEN_FILE="${UPLOAD_TOKEN_FILE:-$CONFIG_DEPOT_DATA_DIR/upload_token}"
SUBSCRIBE_FILE="${SUBSCRIBE_FILE:-$CONFIG_DEPOT_DATA_DIR/subscribe}"
DEPLOY_URL_FILE="${DEPLOY_URL_FILE:-$WORK_DIR/deploy_url}"
CONFIG_OUTPUT_DIR="${CONFIG_OUTPUT_DIR:-$WORK_DIR/config}"
CONFIG_ARCHIVE_FILE="${CONFIG_ARCHIVE_FILE:-$WORK_DIR/config.tar.gz}"
ENCRYPTED_CONFIG_FILE="${ENCRYPTED_CONFIG_FILE:-$WORK_DIR/config.tar.gz.aes}"
DEPLOY_OUTPUT_FILE="${DEPLOY_OUTPUT_FILE:-$WORK_DIR/deploy_config.out}"
SUBCONVERTER_RELEASE_FILE="${SUBCONVERTER_RELEASE_FILE:-$WORK_DIR/release}"
SUBCONVERTER_ASSET_FILE="${SUBCONVERTER_ASSET_FILE:-$WORK_DIR/subconverter.tar.gz}"
SUBCONVERTER_DOWNLOAD_URL="${SUBCONVERTER_DOWNLOAD_URL:-}"
ACL4SSR_ARCHIVE="${ACL4SSR_ARCHIVE:-$WORK_DIR/ACL4SSR.tar.gz}"
SUBSCRIBE_JSON_FILE="${SUBSCRIBE_JSON_FILE:-$WORK_DIR/subscribe.json}"
SUBCONVERTER_LOG_FILE="${SUBCONVERTER_LOG_FILE:-$WORK_DIR/subconverter.log}"
SUBCONVERTER_PID_FILE="${SUBCONVERTER_PID_FILE:-$WORK_DIR/subconverter.pid}"
CONFIG_DEPOT_LOG_FILE="${CONFIG_DEPOT_LOG_FILE:-$WORK_DIR/config-depot.log}"
CONFIG_DEPOT_PID_FILE="${CONFIG_DEPOT_PID_FILE:-$WORK_DIR/config-depot.pid}"
SUBCONVERTER_URL="${SUBCONVERTER_URL:-http://127.0.0.1:25500/sub}"
SUBCONVERTER_HEALTH_URL="${SUBCONVERTER_HEALTH_URL:-http://127.0.0.1:25500/version}"

if [[ -z "${SUBCONVERTER_ASSET_NAME:-}" ]]; then
    case "$(uname -s)-$(uname -m)" in
        Darwin-arm64) SUBCONVERTER_ASSET_NAME="subconverter_darwinarm.tar.gz" ;;
        Darwin-*) SUBCONVERTER_ASSET_NAME="subconverter_darwin64.tar.gz" ;;
        Linux-aarch64 | Linux-arm64) SUBCONVERTER_ASSET_NAME="subconverter_aarch64.tar.gz" ;;
        Linux-*) SUBCONVERTER_ASSET_NAME="subconverter_linux64.tar.gz" ;;
        *)
            echo 不支持自动选择subconverter包，请通过SUBCONVERTER_ASSET_NAME指定，
            exit 9
            ;;
    esac
fi

export ROOT_DIR
export WORK_DIR
export CONFIG_DEPOT_BINARY
export CONFIG_DEPOT_SOURCE_DIR
export CONFIG_DEPOT_DATA_DIR
export CONFIG_DEPOT_ADDR
export GITHUB_TOKEN_FILE
export SUBCONVERTER_DIR
export SUBCONVERTER_BASE_PATH
export ACL4SSR_BASE_PATH
export SUBCONFIG_DIR
export UPLOAD_SECRET_FILE
export UPLOAD_TOKEN_FILE
export SUBSCRIBE_FILE
export DEPLOY_URL_FILE
export CONFIG_OUTPUT_DIR
export CONFIG_ARCHIVE_FILE
export ENCRYPTED_CONFIG_FILE
export DEPLOY_OUTPUT_FILE
export SUBCONVERTER_RELEASE_FILE
export SUBCONVERTER_ASSET_FILE
export SUBCONVERTER_DOWNLOAD_URL
export ACL4SSR_ARCHIVE
export SUBSCRIBE_JSON_FILE
export SUBCONVERTER_LOG_FILE
export SUBCONVERTER_PID_FILE
export CONFIG_DEPOT_LOG_FILE
export CONFIG_DEPOT_PID_FILE
export SUBCONVERTER_URL
export SUBCONVERTER_HEALTH_URL
export SUBCONVERTER_ASSET_NAME

if [[ -r "$GITHUB_TOKEN_FILE" ]]; then
    GITHUB_TOKEN=$(tr -d '\r\n' <"$GITHUB_TOKEN_FILE")
    export GITHUB_TOKEN
fi
