name: 更新订阅配置
env:
  TZ: Asia/Shanghai

on:
  push:
    tags:
      - "*"
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
      - "!.github/workflows/subconverter.yml"
      - "config-depot/**"
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/workflows/*"
      - "!.github/workflows/subconverter.yml"
      - "config-depot/**"
      - "README.md"
  schedule:
    - cron: "0 */2 * * *"
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4

      - name: install dependencies
        run: update-config/install-dependencies.sh

      - name: prepare
        run: update-config/prepare.sh
        env:
          UPLOAD_SECRET: ${{ secrets.upload_secret }}
          UPLOAD_TOKEN: ${{ secrets.upload_token }}
          DEPLOY_URL: ${{ secrets.deploy_url }}
          SUBSCRIBE: ${{ secrets.subscribe }}

      - name: run subconverter
        run: update-config/run-subconverter.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: subconverter/_SubConfig

      - name: cache external config
        run: update-config/cache-external-config.sh

      - name: update config
        run: update-config/update-config.sh

      - name: compress config
        run: update-config/compress-config.sh

      - name: deploy config
        if: ${{ env.deploy == 'true' }}
        run: update-config/deploy-config.sh

      - name: decrypt config
        if: ${{ env.artifact == 'true' }}
        run: update-config/decrypt-config.sh

      - name: upload config
        if: ${{ env.artifact == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: config-decrypt/*
